name: test workflow
on:
 workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: 'Build and Test'
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
